import {memo,useMemo,useState} from 'react';
import {ResponsiveContainer,ScatterChart,Scatter,CartesianGrid,XAxis,YAxis,Tooltip,ReferenceLine} from 'recharts';
import {allMeasures,measureValue,scopeLabel,formatMeasure,type Measure} from '@/lib/measures';
import {pairStats,type Pair} from '@/lib/correlation';
import type {Provider,Tenure} from '@/lib/analysis';
function CorrelationExplorer({providers,tenure}:{providers:Provider[];tenure:Tenure}){
 const [family,setFamily]=useState('both'),[method,setMethod]=useState('pearson'),[xKey,setX]=useState('CH01_1'),[yKey,setY]=useState('TP01');
 const available=allMeasures.filter(m=>tenure!=='LCHO'||m.scope!=='LCRA');
 const catalog=available.filter(m=>m.key==='TP01'||family==='both'||(family==='satisfaction')===m.key.startsWith('TP'));
 const x=available.find(m=>m.key===xKey)??available[0],y=available.find(m=>m.key===yKey)??available[0];
 const pairsFor=(a:Measure,b:Measure):Pair[]=>providers.flatMap(p=>{const xv=measureValue(p,a,tenure),yv=measureValue(p,b,tenure);return xv==null||yv==null?[]:[{id:p.id,name:p.name,x:xv,y:yv}]});
 const pairs=useMemo(()=>pairsFor(x,y),[providers,tenure,x.key,y.key]);
 const stats=pairStats(pairs,method);
 const ranked=catalog.filter(m=>m.key!==y.key).map(m=>({m,stats:pairStats(pairsFor(m,y),method)})).filter(v=>v.stats!==null).sort((a,b)=>Math.abs(b.stats!.r)-Math.abs(a.stats!.r));
 const picker=(label:string,value:string,change:(v:string)=>void)=><label className="corr-control">{label}<select value={value} onChange={e=>change(e.target.value)}>{available.map(m=><option key={m.key} value={m.key}>{m.key} · {m.label}</option>)}</select></label>;
 const min=Math.min(...pairs.map(p=>p.x)),max=Math.max(...pairs.map(p=>p.x));
 return <section className="correlation-section correlation-explorer"><div className="correlation-heading"><div className="eyebrow">WHAT MOVES TOGETHER?</div><h2>Correlation explorer</h2><p>Satisfaction and operations · {tenure==='all'?'LCRA / combined':tenure} · {providers.length} filtered associations</p></div>
 <div className="corr-controls"><label className="corr-control">Ranking & matrix measures<select value={family} onChange={e=>setFamily(e.target.value)}><option value="both">All TSM measures</option><option value="satisfaction">Satisfaction · TP</option><option value="operational">Operational + TP01</option></select></label><label className="corr-control">Correlation<select value={method} onChange={e=>setMethod(e.target.value)}><option value="pearson">Pearson · linear relationship</option><option value="spearman">Spearman · rank relationship</option></select></label>{picker('Outcome · Y',y.key,setY)}{picker('Compare with · X',x.key,setX)}</div>
 <div className="reg-grid"><section className="reg-card"><div className="reg-card-heading"><div><span className="eyebrow">PAIRWISE RELATIONSHIP</span><h2>{x.key} × {y.key}</h2><p>{stats?`${method==='pearson'?'r':'ρ'} = ${stats.r.toFixed(3)} · n = ${stats.n}`:`${pairs.length} paired observations · correlation unavailable`}</p></div></div><p className="reg-footnote">X: {x.label} · {scopeLabel(x,tenure)}. Y: {y.label} · {scopeLabel(y,tenure)}.</p>
 {pairs.length?<div className="reg-chart reg-scatter"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{top:20,right:25,left:15,bottom:30}}><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" dataKey="x" domain={['auto','auto']} tick={{fontSize:11}} label={{value:`${x.key} (${x.unit})`,position:'bottom',offset:10,fontSize:12}}/><YAxis type="number" dataKey="y" domain={['auto','auto']} tick={{fontSize:11}} label={{value:`${y.key} (${y.unit})`,angle:-90,position:'insideLeft',fontSize:12}}/><Tooltip content={({active,payload})=>{const p=payload?.[0]?.payload as Pair|undefined;return active&&p?<div className="reg-tooltip"><strong>{p.name}</strong><span>{x.key}: {formatMeasure(p.x,x.unit)}</span><span>{y.key}: {formatMeasure(p.y,y.unit)}</span></div>:null}}/><Scatter data={pairs} fill="#013d5b" fillOpacity={.6} isAnimationActive={false}/>{stats&&<ReferenceLine segment={[{x:min,y:stats.intercept+stats.slope*min},{x:max,y:stats.intercept+stats.slope*max}]} stroke="#ca2c27" strokeWidth={2} ifOverflow="extendDomain"/>}</ScatterChart></ResponsiveContainer></div>:<p className="corr-empty">No paired observations match these measures and filters.</p>}
 <p className="reg-footnote">Line: ordinary least-squares fit on the raw values, without controls (also when displaying Spearman). Correlation needs at least three pairs and variation in both measures.</p></section>
 <section className="reg-card"><span className="eyebrow">STRONGEST RELATIONSHIPS WITH {y.key}</span><h2>Positive and negative associations</h2><p className="reg-footnote">Ranked by |{method==='pearson'?'r':'ρ'}|. Select a row to plot it. Every pair can have a different sample.</p><div className="corr-rankings">{ranked.length?ranked.map(({m,stats:s})=><button key={m.key} className={x.key===m.key?'active':''} onClick={()=>setX(m.key)}><span><b>{m.key}</b> · {m.label}<small>n = {s!.n} · {m.unit}</small></span><strong style={{color:s!.r<0?'#ca2c27':'#013d5b'}}>{s!.r>0?'+':''}{s!.r.toFixed(2)}</strong></button>):<p>No non-constant pairs available.</p>}</div></section></div>
 <details className="corr-matrix-wrap" open><summary>Interactive correlation matrix</summary><p className="reg-footnote">Click a cell to select X (column) and Y (row). Hover for labels and pair count. Blue = positive; red = negative; grey = unavailable. Scroll horizontally to explore all measures.</p><div className="corr-matrix-scroll"><table className="corr-matrix"><thead><tr><th scope="col">Y ↓ / X →</th>{catalog.map(m=><th scope="col" key={m.key} title={m.label}>{m.key}</th>)}</tr></thead><tbody>{catalog.map(a=><tr key={a.key}><th scope="row" title={a.label}>{a.key}</th>{catalog.map(b=>{const s=pairStats(pairsFor(b,a),method);return <td key={b.key}><button onClick={()=>{setX(b.key);setY(a.key)}} aria-label={`${a.key} ${a.label} versus ${b.key} ${b.label}: ${s?`${s.r.toFixed(2)}, n ${s.n}`:'unavailable'}`} title={`${a.label} × ${b.label}\n${s?`${method}: ${s.r.toFixed(3)} · n=${s.n}`:'Missing or constant values / fewer than 3 pairs'}`} style={{background:s?`rgba(${s.r<0?'202,44,39':'1,61,91'},${.08+.8*Math.abs(s.r)})`:'#edf0f2',color:s&&Math.abs(s.r)>.6?'white':'#013d5b',outline:x.key===b.key&&y.key===a.key?'2px solid #f3bb39':undefined}}>{s?s.r.toFixed(2):'—'}</button></td>})}</tr>)}</tbody></table></div></details>
 <p className="correlation-note">All explorer filters apply, including association selection and the map’s value range. Analysis always uses 2024/25 levels, even when the map shows YoY. Pairwise complete cases; no imputation or weighting. BS/NM measures cover combined tenures, RP is LCRA-only and CH follows the selected tenure. These are exploratory provider-level associations, not causal effects; selection, multiple comparisons and reporting practices can affect results.</p></section>
}

export default memo(CorrelationExplorer);
