import { useEffect, useMemo, useState } from 'react';
import { BarChart, Bar, Cell, CartesianGrid, XAxis, YAxis, Tooltip, ResponsiveContainer, ScatterChart, Scatter, ReferenceLine, LineChart, Line } from 'recharts';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';

type Feature={unit?:string;scope?:string;key:string;label:string;kind:'numeric'|'region';group:string;coefficient:number;rawCoefficient:number;mean:number;sd:number;foldMin:number;foldMax:number};
type Point={id:string;name:string;region:string;stock:number;actual:number;predicted:number;fitted:number;residual:number;fold:number;x:number[];featureX?:number;adjusted?:number};
type Metrics={rmse:number;mae:number;r2:number};
type Model={tenure:string;n:number;eligible:number;excluded:{id:string;name:string;reason:string}[];featureCount:number;alpha:number;alphaAtBoundary:boolean;referenceRegion:string;regionCounts:Record<string,number>;targetMean:number;metrics:Metrics;baseline:Metrics;features:Feature[];points:Point[];curve:{alpha:number;logAlpha:number;rmse:number}[];ablations:{group:string;rmseWithout:number;rmseIncrease:number}[]};
type Results={dataYear:string;models:Record<'LCRA'|'LCHO',Model>;operationalModels:Record<'LCRA'|'LCHO',Model>};
const blue='#013d5b',red='#ca2c27',gold='#f3bb39';
const fixed=(n:number,d=2)=>Number.isFinite(n)?n.toFixed(d):'—';
const signed=(n:number)=>`${n>0?'+':''}${fixed(n)}`;
function PointTip({active,payload,adjusted=false}:{active?:boolean;payload?:readonly {payload?:Point}[];adjusted?:boolean}){
 const p=payload?.[0]?.payload;if(!active||!p)return null;
 return <div className="reg-tooltip"><strong>{p.name}</strong><span>{p.region} · {p.stock.toLocaleString('en-GB')} homes</span><span>Observed TP01: {fixed(p.actual,1)}%</span>{adjusted?<span>Adjusted TP01: {fixed(p.adjusted??0,1)}%</span>:<><span>Held-out prediction: {fixed(p.predicted,1)}%</span><span>Residual: {signed(p.residual)} pp · fold {p.fold}</span></>}</div>
}
export default function Regression(){
 const [results,setResults]=useState<Results|null>(null),[error,setError]=useState(false),[tenure,setTenure]=useState<'LCRA'|'LCHO'>('LCRA'),[featureKey,setFeatureKey]=useState('TP06');
 useEffect(()=>{fetch(`${import.meta.env.BASE_URL}regression.json`).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<Results>}).then(setResults).catch(()=>setError(true))},[]);
 const [family,setFamily]=useState<'satisfaction'|'operational'>('satisfaction');
 const model=results?.[family==='satisfaction'?'models':'operationalModels'][tenure];
 const numeric=useMemo(()=>model?.features.filter(f=>f.kind==='numeric').sort((a,b)=>Math.abs(b.coefficient)-Math.abs(a.coefficient))??[],[model]);
 const feature=numeric.find(f=>f.key===featureKey)??numeric[0];
 const adjusted=useMemo(()=>{if(!model||!feature)return [];const k=model.features.findIndex(f=>f.key===feature.key);return model.points.map(p=>({...p,featureX:p.x[k],adjusted:p.actual-p.fitted+feature.rawCoefficient*(p.x[k]-feature.mean)+model.targetMean}))},[model,feature]);
 const histogram=useMemo(()=>{if(!model)return [];const max=Math.max(...model.points.map(p=>Math.abs(p.residual)),2);const step=Math.max(1,Math.ceil(max/6));return Array.from({length:12},(_,i)=>{const low=(i-6)*step,high=low+step;return {label:`${low} to ${high}`,count:model.points.filter(p=>p.residual>=low&&(i===11?p.residual<=high:p.residual<high)).length}})},[model]);
 if(!model)return <div className="reg-loading" role="status">{error?<><h2>Regression results couldn’t be loaded.</h2><button onClick={()=>location.reload()}>Retry</button></>:<h2>Loading regression results…</h2>}</div>;
 const selectedFeature=feature!;
 const minX=Math.min(...adjusted.map(p=>p.featureX!)),maxX=Math.max(...adjusted.map(p=>p.featureX!));
 const lineY=(x:number)=>model.targetMean+selectedFeature.rawCoefficient*(x-selectedFeature.mean);
 const regions=model.features.filter(f=>f.kind==='region').map(f=>({...f,label:`${f.label} (n=${model.regionCounts[f.label]})`}));
 return <div className="regression-page"><div className="reg-heading"><div><div className="eyebrow">TENANT SATISFACTION · RIDGE REGRESSION</div><h1>What predicts overall satisfaction?</h1><p>Separate models of TP01, using either satisfaction or operational measures, with association size and region controls.</p></div><Tabs value={tenure} onValueChange={v=>setTenure(v as 'LCRA'|'LCHO')}><TabsList className="reg-tenure" aria-label="Regression tenure"><TabsTrigger value="LCRA">LCRA · rental</TabsTrigger><TabsTrigger value="LCHO">LCHO · ownership</TabsTrigger></TabsList></Tabs></div>
 <div className="reg-family"><label className="corr-control">Predictor family<select aria-label="Regression predictor family" value={family} onChange={e=>setFamily(e.target.value as 'satisfaction'|'operational')}><option value="satisfaction">Satisfaction · TP measures + size + region</option><option value="operational">Operational · RP / CH / BS / NM + size + region</option></select></label></div>
 <div className="reg-scope"><span className="pill">{tenure} · {results!.dataYear}</span><span>Full national cohort · explorer filters do not apply</span><span>{family==='operational'?'CH follows the selected tenure; BS/NM cover combined tenures. RP included for LCRA only.':tenure==='LCHO'?'TP02–TP04 are not applicable and are excluded.':'TP02–TP12 included.'}</span></div>
 <div className="reg-stats"><div><span>Associations modelled</span><strong>{model.n}<small>/ {model.eligible} with TP01</small></strong><p>{model.excluded.length} excluded for incomplete predictors</p></div><div><span>Held-out R²</span><strong>{fixed(model.metrics.r2)}</strong><p>Five outer validation folds</p></div><div><span>Held-out RMSE</span><strong>{fixed(model.metrics.rmse)}<small>pp</small></strong><p>Mean-only baseline: {fixed(model.baseline.rmse)} pp</p></div><div><span>Selected ridge penalty · α</span><strong>{Number(model.alpha.toPrecision(4))}</strong><p>{model.featureCount} features · unpenalized intercept</p></div></div>
 <div className="reg-leaders">{numeric.slice(0,3).map((f,i)=><button key={f.key} onClick={()=>setFeatureKey(f.key)} className={selectedFeature.key===f.key?'reg-leader active':'reg-leader'}><span className="reg-rank">0{i+1}</span><div><span className="eyebrow">{f.key==='size'?'SIZE':f.key}</span><h3>{f.label}</h3><p>Adjusted association per 1 SD</p></div><strong style={{color:f.coefficient>=0?blue:red}}>{signed(f.coefficient)}<small>pp TP01</small></strong></button>)}</div>
 <p className="reg-caution">Coefficients describe conditional associations, not causal effects or significance tests. Correlated predictors share signal; rankings can change with the cohort and penalty.{tenure==='LCHO'?` With only ${model.n} observations, treat the LCHO ranking as exploratory.`:''} {family==='operational'?'Operational models omit TP02–TP12: these coefficients are not adjusted for the other satisfaction measures. Model families may use different complete-case cohorts, so performance differences are not a controlled feature-set comparison.':''}</p>
 <div className="reg-grid"><section className="reg-card"><div className="reg-card-heading"><div><span className="eyebrow">ADJUSTED ASSOCIATIONS</span><h2>Which measures carry the most signal?</h2><p>TP01 percentage points per one standard deviation of each numeric predictor.</p></div></div><div className="reg-chart" style={{height:Math.max(330,numeric.length*34)}}><ResponsiveContainer width="100%" height="100%"><BarChart data={numeric.map(f=>({...f,chartLabel:f.key==='size'?'log₁₀ homes':`${f.key} · ${f.label}`}))} layout="vertical" margin={{left:5,right:25,top:10,bottom:15}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tick={{fontSize:12}} label={{value:'Adjusted TP01 change (pp / SD)',position:'bottom',offset:0,fontSize:12}}/><YAxis dataKey="chartLabel" type="category" width={180} tick={{fontSize:11}} interval={0}/><Tooltip cursor={{fill:'#edf4f9'}} formatter={(v)=>[`${fixed(Number(v))} pp per SD`,'Coefficient']}/><ReferenceLine x={0} stroke="#627785"/><Bar dataKey="coefficient" radius={[0,3,3,0]} isAnimationActive={false}>{numeric.map(f=><Cell key={f.key} fill={f.coefficient>=0?blue:red}/>)}</Bar></BarChart></ResponsiveContainer></div><p className="reg-footnote">Size is log₁₀ owned homes in this tenure. Coefficients come from a final fit on the full modelling cohort; prediction diagnostics use held-out fits.</p></section>
 <section className="reg-card"><div className="reg-card-heading"><div><span className="eyebrow">OUT-OF-SAMPLE CHECK</span><h2>Observed versus predicted TP01</h2><p>Each association is predicted by a model that did not train on it.</p></div></div><div className="reg-chart reg-scatter"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{top:20,right:25,bottom:30,left:10}}><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" dataKey="actual" domain={[0,100]} name="Observed TP01" tick={{fontSize:12}} label={{value:'Observed TP01 (%)',position:'bottom',offset:10,fontSize:12}}/><YAxis type="number" dataKey="predicted" domain={['auto','auto']} name="Held-out prediction" tick={{fontSize:12}} label={{value:'Predicted TP01 (%)',angle:-90,position:'insideLeft',fontSize:12}}/><Tooltip cursor={{strokeDasharray:'3 3'}} content={<PointTip/>}/><ReferenceLine segment={[{x:0,y:0},{x:100,y:100}]} stroke={red} strokeDasharray="5 5" ifOverflow="extendDomain"/><Scatter data={model.points} fill={blue} fillOpacity={.65} isAnimationActive={false}/></ScatterChart></ResponsiveContainer></div><p className="reg-footnote">Dashed line: perfect agreement. Hover for provider details. MAE = {fixed(model.metrics.mae)} pp. Predictions are not clipped to 0–100%.</p></section>
 <section className="reg-card"><div className="reg-card-heading"><div><span className="eyebrow">EXPLORE A PREDICTOR</span><h2>Adjusted relationship</h2></div><Select value={selectedFeature.key} onValueChange={v=>v&&setFeatureKey(v)}><SelectTrigger className="reg-picker" aria-label="Regression feature"><SelectValue>{selectedFeature.key==='size'?'Association size':`${selectedFeature.key} · ${selectedFeature.label}`}</SelectValue></SelectTrigger><SelectContent>{numeric.map(f=><SelectItem key={f.key} value={f.key}>{f.key==='size'?'Association size':`${f.key} · ${f.label}`}</SelectItem>)}</SelectContent></Select></div><p className="reg-chart-intro">Other fitted feature contributions removed from TP01; mean TP01 retained.</p><div className="reg-chart reg-scatter"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{top:15,right:25,bottom:32,left:10}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="featureX" type="number" domain={['dataMin','dataMax']} tick={{fontSize:12}} tickFormatter={v=>fixed(v,1)} label={{value:selectedFeature.key==='size'?'log₁₀ owned homes':`${selectedFeature.key} (${selectedFeature.unit??'%'})`,position:'bottom',offset:10,fontSize:12}}/><YAxis dataKey="adjusted" type="number" domain={['auto','auto']} tick={{fontSize:12}} label={{value:'Adjusted TP01 (%)',angle:-90,position:'insideLeft',fontSize:12}}/><Tooltip content={<PointTip adjusted/>}/><Scatter data={adjusted} fill={blue} fillOpacity={.55} isAnimationActive={false}/><ReferenceLine segment={[{x:minX,y:lineY(minX)},{x:maxX,y:lineY(maxX)}]} stroke={red} strokeWidth={2} ifOverflow="extendDomain"/></ScatterChart></ResponsiveContainer></div><p className="reg-footnote">Partial-residual view of the final fitted model, not held-out validation. Slope: {signed(selectedFeature.rawCoefficient)} pp per {selectedFeature.key==='size'?'tenfold increase in homes':selectedFeature.unit==='%'?'1 percentage point':'1 case per 1,000 homes'}. One SD = {fixed(selectedFeature.sd)} {selectedFeature.key==='size'?'log₁₀ homes':selectedFeature.unit==='%'?'pp':'cases per 1,000 homes'}.</p></section>
 <section className="reg-card"><div className="reg-card-heading"><div><span className="eyebrow">REGIONAL DIFFERENCES</span><h2>Region after adjusting for other features</h2><p>TP01 percentage-point difference from London (n={model.regionCounts.London}).</p></div></div><div className="reg-chart" style={{height:260}}><ResponsiveContainer width="100%" height="100%"><BarChart data={regions} layout="vertical" margin={{left:10,right:25,bottom:15}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tick={{fontSize:12}}/><YAxis type="category" dataKey="label" width={120} tick={{fontSize:12}}/><Tooltip formatter={v=>[`${fixed(Number(v))} pp`,'Difference vs London']}/><ReferenceLine x={0} stroke="#627785"/><Bar dataKey="coefficient" isAnimationActive={false}>{regions.map(f=><Cell key={f.key} fill={f.coefficient>=0?blue:red}/>)}</Bar></BarChart></ResponsiveContainer></div><p className="reg-footnote">Uses the source’s predominant-region categories. “Mixed” means no single predominant region. Region indicators are standardized during fitting, then converted back to categorical contrasts here.</p><div className="reg-region-reference">London reference coefficient: 0 pp · all other predictors held fixed</div></section>
 <section className="reg-card"><div className="reg-card-heading"><div><span className="eyebrow">DOES A FEATURE GROUP HELP?</span><h2>Incremental predictive value</h2><p>Increase in held-out RMSE when a feature group is removed.</p></div></div><div className="reg-chart" style={{height:240}}><ResponsiveContainer width="100%" height="100%"><BarChart data={model.ablations} layout="vertical" margin={{left:5,right:25,bottom:15}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tick={{fontSize:12}}/><YAxis dataKey="group" type="category" width={110} tick={{fontSize:12}}/><Tooltip formatter={v=>[`${signed(Number(v))} pp`,'RMSE without − full model']}/><ReferenceLine x={0} stroke="#627785"/><Bar dataKey="rmseIncrease" isAnimationActive={false}>{model.ablations.map(a=><Cell key={a.group} fill={a.rmseIncrease>=0?blue:red}/>)}</Bar></BarChart></ResponsiveContainer></div><p className="reg-footnote">Positive: removing the group worsens prediction. Negative: the reduced model predicts better. Each reduced model retunes α within the same outer splits. This is a descriptive comparison, not a significance test.</p></section>
 <section className="reg-card"><div className="reg-card-heading"><div><span className="eyebrow">ERROR DISTRIBUTION</span><h2>Where does the model miss?</h2><p>Held-out residual = observed TP01 − predicted TP01.</p></div></div><div className="reg-chart" style={{height:240}}><ResponsiveContainer width="100%" height="100%"><BarChart data={histogram} margin={{right:20,left:0,bottom:30}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tick={{fontSize:10}} angle={-35} textAnchor="end" interval={1}/><YAxis allowDecimals={false} tick={{fontSize:12}}/><Tooltip formatter={v=>[v,'Associations']} labelFormatter={v=>`${v} pp`}/><Bar dataKey="count" fill={gold} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><p className="reg-footnote">Positive residuals are under-predictions; negative residuals are over-predictions. Bin counts cover every modelled association.</p></section>
 <section className="reg-card reg-wide"><div className="reg-card-heading"><div><span className="eyebrow">REGULARIZATION</span><h2>Choosing the ridge penalty</h2><p>Five-fold tuning error for the final model · α shown on a logarithmic scale.</p></div></div><div className="reg-chart" style={{height:260}}><ResponsiveContainer width="100%" height="100%"><LineChart data={model.curve} margin={{top:10,right:30,left:10,bottom:25}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="alpha" type="number" scale="log" domain={[.001,10000]} ticks={[.001,.01,.1,1,10,100,1000,10000]} tick={{fontSize:12}}/><YAxis domain={['auto','auto']} tick={{fontSize:12}} label={{value:'CV RMSE (pp)',angle:-90,position:'insideLeft',fontSize:12}}/><Tooltip formatter={v=>[`${fixed(Number(v))} pp`,'Tuning RMSE']} labelFormatter={v=>`α = ${Number(Number(v).toPrecision(4))}`}/><ReferenceLine x={model.alpha} stroke={red} strokeDasharray="5 5" label={{value:'Selected α',position:'insideTopRight',fill:red,fontSize:12}}/><Line type="linear" dataKey="rmse" stroke={blue} dot={false} strokeWidth={2} isAnimationActive={false}/></LineChart></ResponsiveContainer></div><p className="reg-footnote">The final α is chosen on the full cohort. Headline performance uses separate outer validation folds, each with its own inner tuning. {model.alphaAtBoundary?'Selected α is at the search boundary; treat the tuning result cautiously.':''}</p></section></div>
 <details className="reg-method"><summary>Model specification, coefficient details and limitations</summary><div><p><b>Target:</b> 2024/25 TP01 satisfaction in percentage points. <b>Sample:</b> {model.n} non-profit providers with complete applicable predictors; each provider receives equal weight. {model.excluded.length>0?`Excluded: ${model.excluded.map(p=>p.name).join('; ')}.`:'No eligible TP01 observations were excluded.'}</p><p><b>Features:</b> log₁₀ owned homes for {tenure}, {family==='operational'?model.features.filter(f=>f.group==='Operational measures').map(f=>f.key).join(', '):tenure==='LCRA'?'TP02–TP12':'TP05–TP12'}, and four region indicators with London as reference. Each feature is centered and scaled using only its training fold. All coefficients except the intercept receive an L2 penalty. Objective: Σ(y − ŷ)² + αΣβ².</p><p>{family==='operational'?'Operational percentages and rates per 1,000 homes enter in their published units before standardization. RP01 is homes failing the Decent Homes Standard; RP02 uses provider-specific repair targets. Complaints/ASB rates reflect reporting as well as underlying problems. BS/NM cover combined tenure stock even in the LCHO model. No missing, suppressed or inapplicable values are imputed.':''}</p><p><b>Validation:</b> five shuffled outer folds; five shuffled inner folds select α over 29 logarithmically spaced values from 0.001 to 10,000 by mean squared error. Pooled held-out R², RMSE and MAE use one out-of-fold prediction per provider. The baseline predicts each training fold’s mean. The final explanatory fit is then trained on all complete observations with a separately tuned α.</p><p><b>Limitations:</b> same-year provider-level associations; no causal interpretation, survey weighting, survey-method adjustment or inferential p-values. Regions are broad source categories. Complete-case selection can bias results. Correlated predictors can make individual coefficient signs and rankings unstable. Fold ranges below are sensitivity diagnostics, not confidence intervals. Models use the full data snapshot and do not respond to explorer filters.</p><div className="reg-coefficient-list">{model.features.map(f=><div key={f.key}><span>{f.kind==='region'?`Region: ${f.label} vs London`:`${f.key} · ${f.label}`}</span><b>{signed(f.coefficient)} pp{f.kind==='numeric'?'/SD':''}</b><small>Outer-fold range: {fixed(f.foldMin)} to {fixed(f.foldMax)}</small></div>)}</div><p>Reproduce with <code>scripts/fit-regression.py</code> and the pinned requirements in the public repository. Results and the source-data checksum are bundled in <code>public/regression.json</code>. <a href="https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html" target="_blank" rel="noreferrer">Ridge specification ↗</a></p></div></details>
 </div>
}
