export type Tenure='all'|'LCRA'|'LCHO';
export type TenureData={stock:number;areas:{id:string;name:string;stock:number}[];scores:(number|null)[];previous:(number|null)[];sample:number|null;survey:string|null;url:string|null;lon:number|null;lat:number|null;unlocatedStock:number};
export type Provider={id:string;name:string;stock:number;areas:{id:string;name:string;stock:number}[];rent:number|null;scores:(number|null)[];previous:(number|null)[];survey:string|null;sample:number|null;comment:string;url:string|null;members:string[];lon:number|null;lat:number|null;region:string;operational?:Record<'LCRA'|'LCHO',{values:Record<string,number|null>;previous:Record<string,number|null>}>;tenures:Record<'LCRA'|'LCHO',TenureData>};
export function projectTenure(ps:Provider[],tenure:Tenure):Provider[]{return tenure==='all'?ps:ps.filter(p=>p.tenures[tenure].stock>0).map(p=>({...p,...p.tenures[tenure],rent:tenure==='LCHO'?null:p.rent})).sort((a,b)=>b.stock-a.stock)}
export type Filters={query:string;region:string;size:number[];rent:number[];knownRent:boolean;selectedIds?:string[];metric?:number;mode?:string;scoreRange?:number[];reportedScoreOnly?:boolean;scoreBounds?:number[]};
export function displayedValue(p:Provider,index:number,mode:string):number|null{const a=p.scores[index],b=p.previous[index];return a==null?null:mode==='change'?(b==null?null:a-b):a}
export function filterProviders(ps:Provider[],f:Filters){return ps.filter(p=>{
 const value=displayedValue(p,f.metric??0,f.mode??'score');const limits=f.scoreRange??(f.mode==='change'?[-100,100]:[0,100]);const bounds=f.scoreBounds??(f.mode==='change'?[-100,100]:[0,100]);const rangeActive=limits[0]>bounds[0]||limits[1]<bounds[1];
 return p.name.toLowerCase().includes(f.query.toLowerCase())&&(!f.selectedIds?.length||f.selectedIds.includes(p.id))&&(f.region==='All regions'||p.region===f.region)&&p.stock>=f.size[0]&&(f.size[1]===120000||p.stock<=f.size[1])&&(p.rent===null?(!f.knownRent&&f.rent[0]===0&&f.rent[1]===300):p.rent>=f.rent[0]&&(f.rent[1]===300||p.rent<=f.rent[1]))&&(value===null?(!rangeActive&&!f.reportedScoreOnly):value>=limits[0]-1e-9&&value<=limits[1]+1e-9)
})}
export function correlations(ps:Provider[]){return Array.from({length:11},(_,k)=>{const index=k+1;const pairs=ps.filter(p=>p.scores[0]!==null&&p.scores[index]!==null).map(p=>[p.scores[0]!,p.scores[index]!]);const n=pairs.length;if(n<3)return null;const mx=pairs.reduce((s,p)=>s+p[0],0)/n,my=pairs.reduce((s,p)=>s+p[1],0)/n;let xx=0,yy=0,xy=0;for(const [x,y] of pairs){xx+=(x-mx)**2;yy+=(y-my)**2;xy+=(x-mx)*(y-my)}return xx&&yy?{index,n,r:xy/Math.sqrt(xx*yy)}:null}).filter((v):v is {index:number;n:number;r:number}=>v!==null).sort((a,b)=>b.r-a.r)}
